name: This is a demo for github actions python operations
run-name: github action demo

on:
  push:
    branches:
      - feature/GTP-00100-github-action-python-operations
  
  workflow_dispatch:
    inputs:
      project-name:
        description: 'the name for this project'
        required: false
        default: 'devops project'

jobs:
  # job name
  check-system-info:
    runs-on: ubuntu-latest
    steps:
      - name: Show memory info
        id: memory-info
        shell: bash
        run: |
          echo "Here we will show the memory info"
          free -h

      - name: Show disk info
        id: disk-info
        shell: bash
        run: |
          echo "Here we will show the disk info"
          df -TH

      - name: Show current working directory
        id: working-directory
        shell: bash
        run: |
          echo "Here we will show the current working directory"
          echo "$(pwd)"
      
      - name: Create files in working directory
        id: create-files
        shell: bash
        run: |
          echo "We are creating files in this working directory"
          echo "hello world, hello China!" > test1.txt
          echo "this is the day I have been working" > test2.txt
          echo "I love zhengjiao very much!" > test3.txt
          cat test1.txt

      - name: Create folders in working directory
        id: create-folders
        shell: bash
        run: |
          echo "We are creating multiple folders in this working directory"
          mkdir -p devops_tools/jave_tool/sector1
          mkdir sre_tools
        
      - name: Show the folders and files list
        id: files-folders-list
        shell: bash
        run: |
          echo "Here is the list for files and folders"
          ls -la
    
      - name: Show the size of the folder
        id: folder-size
        shell: bash
        run: |
          echo "Here we will show the folder size"
          echo "total size is: $(du -sh .)"

      - name: Show all users in runner
        id: show-users
        shell: bash
        run: |
          echo "Here will show all users in runner"
          cat /etc/passwd | cut -d: -f1
    
      - name: Show who am i 
        id: who-you-are
        shell: bash
        run: |
          echo "Here will show who you are"
          whoami

      - name: Switch to root user
        id: switch-root
        shell: bash
        run: |
          echo "Here we will swiitch to user user"
          sudo whomai

          



    











